config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
  # resources :webpages
  get '/webpages', to: 'webpages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    #タイトル
    validates :title, presence: true
    validates :title, length: { in: 1..140 }

    #内容
    validates :content, presence: true
    validates :content, length: { in: 1..140 }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action:set_blog, only:[:show, :edit, :update, :destroy]

  #HOME、一覧画面を表示
  def index
    @blog = Blog.all
  end

  #詳細画面
  def show
  end

  #編集画面
  def edit
  end

  #編集処理
  def update
    if @blog.update(blog_params)
      #成功の場合
      redirect_to blogs_path, notice: 'ブログの編集が完了しました'
    else
      #失敗の場合
      render 'edit'
    end
  end

  #削除処理
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: 'ブログの削除が完了しました'
  end

  #新規作成画面
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  #新規作成処理
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      #成功の場合
      
      #一覧画面へリダイレクト
      redirect_to blogs_path, notice:'新規登録処理が完了しました'
    else
      #失敗の場合

      #新規作成画面を再描画
      render 'new'
    end
  end

  def confirm
    @blog = Blog.new(blog_params)
    render:new if @blog.invalid?
  end

  private

  #ストロングパラメータ
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  #ブログ情報のセット
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/webpages_controller.rb
class WebpagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/webpages_helper.rb
module WebpagesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url:choose_new_or_edit) do |form| %>
  
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%=msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  
  <%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model:@blog, url:blogs_path, local:true) do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
    
    <p>タイトル：<%= @blog.title %></p>
    <p>本文：<%= @blog.content %></p>
    <%= form.submit "送信する" %>
<% end %>


<%= form_with(model:@blog, url:new_blog_path, local:true, method:'get') do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
    <%= form.submit "戻る",name:'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>Listing Blogs</h1>

<div class="container">
  <div id="new-blog-link">
    <%= link_to '新規ブログを作成する', new_blog_path %>
  </div>

  <div class="row">
    <% @blog.each do |blog| %>
      <div class="col-xs-12 col-md-6 blog-panel">
        <h2><%= blog.title %></h2>
        <p><%= blog.content %></p>
        <p><%= blog.created_at %></p>
        <div class="blog-links">
          <%= link_to 'Show', blog, class: 'btn btn-default' %>
          <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-info' %> |
          <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br /><br /><br /><br /><br />
前のやつ

<h1>ブログ一覧</h1>

<% if @blog.count == 0 %>
  <!-- ０件だったら、投稿無い旨表示する -->
  <p>まだ投稿がありません。新規に投稿してください</p>

<% else %>

  <table border="1">
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>

    <% @blog.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.content %></td>
      <td><%= link_to '詳細確認', blog_path(blog.id) %></td>
      <td><%= link_to '編集', edit_blog_path(blog.id) %></td>
      <td><%= link_to '削除', blog_path(blog.id), data:{confirm: '削除していいですか？'},method: :delete %></td>
    </tr>
    <% end %>
  </table>

<% end %>

<p><%= link_to '新しくブログを投稿する', new_blog_path %></p>

app/views/blogs/new.html.erb
<h1>新規登録画面</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>

<p><%= link_to 'HOMEへ戻る', blogs_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="card text-center">
        <div class="card-header">
          <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
              <a class="nav-link active" href="#">TOP</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">取引先情報</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">お知らせ</a>
            </li>
          </ul>
        </div>
      </div>
    </header>

    <%= yield %>

    <footer>
      フッター
    </footer>
  </body>
</html>

app/views/webpages/index.html.erb
<article class="container bg-info">
  <h1>取引先情報</h1>
  <ul>
      <li class="col-xs-12 col-sm-6 col-md-4">株式会社ABC</li>
      <li class="col-xs-12 col-sm-6 col-md-4">株式会社DEF</li>
      <li class="col-xs-12 col-sm-6 col-md-4">GHI株式会社</li>
      <li class="col-xs-12 col-sm-6 col-md-4">（株）JKL</li>
      <li class="col-xs-12 col-sm-6 col-md-4">MN（株）</li>
      <li class="col-xs-12 col-sm-6 col-md-4">OPQ（株）</li>
  </ul>
</article>

<article class="container bg-success">
  <h1>お知らせ</h1>
  <ul>
      <li class="col-xs-12 col-sm-6 col-md-3">ソリューション「ZiDOMA data」のユーザー事例がIT Search＋に掲載されました。</li>
      <li class="col-xs-12 col-sm-6 col-md-3">ソリューション「ZiDOMA data」の紹介ページをリニューアルしました。</li>
      <li class="col-xs-12 col-sm-6 col-md-3">～キャリア採用72%が社員紹介による入社～ 採用活動に関するプレスリリースを配信しました。</li>
      <li class="col-xs-12 col-sm-6 col-md-3">弊社広報担当が読売新聞のくらし・家庭面で、働く女性をテーマにした「Woman」に掲載されました。</li>
  </ul>
</article>

<article class="container bg-warning">
  <button type="button" class="btn btn-danger">危険人物</button>

  <div class="card" style="width: 18rem;margin:20px;">
    <img class="card-img-top" src="/assets/girls.png" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>

</article>